env:
  browser: true
  node: true
  es6: true
parserOptions:
  sourceType: module
extends: 'eslint:recommended'
globals:
  chrome: false
rules:
  semi: error
  no-console:
    - error
    - allow:
        - 'info'
        - 'warn'
        - 'error'
  no-empty:
    - error
    - allowEmptyCatch: true
  comma-dangle:
    - error
    - always-multiline
  object-shorthand:
    - error
    - always
  quotes:
    - warn
    - single
    - avoidEscape: true
  no-shadow:
    - error
  no-var:
    - error
  eol-last:
    - error
  no-irregular-whitespace:
    - error
    - skipStrings: true
      skipComments: false
      skipRegExps: true
      skipTemplates: true
