env:
  browser: true
  es6: true
extends: 'eslint:recommended'
globals:
  chrome: false
rules:
  semi: error
  no-console:
    - error
    - allow:
        - 'info'
        - 'warn'
        - 'error'
  no-empty:
    - error
    - allowEmptyCatch: true
  comma-dangle:
    - error
    - always-multiline
  object-shorthand:
    - error
    - always
  quotes:
    - warn
    - single
    - avoidEscape: true
